# Generated by Django 4.2.10 on 2024-02-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("word", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="audio",
            field=models.FileField(
                blank=True, null=True, upload_to="word-audio", verbose_name="Аудио"
            ),
        ),
    ]
