# Generated by Django 4.2.10 on 2024-02-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="audio",
            field=models.FileField(
                blank=True, null=True, upload_to="story-audio", verbose_name="Аудио"
            ),
        ),
    ]
